### ISSUE TITLE
Camera management

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#123]
Seems strange that CameraInterface (Qt) owns a camera, I think it could be better for the Qt part to trigger action (like rotate around) on the camera, which should be own by the renderer for instance

**Comment by Zouch** [comment]
I think this was due to the way we (Maurizio in this case) implemented the "engine camera" in the first place (as a simple interface mostly containing two matrices that you manipulate in a bit low-level way).
And with this implementation we just give two matrices to the renderer and we have a clean interface for the rendering. 

Now, we could indeed have the renderer own a higher level camera, with "real life" properties directly manipulated by the event handling functions

**Comment by MathiasPaulin** [comment]
This must be awaken as it participate to the bug #314 Crash on reset scene
