### ISSUE TITLE
Astroboy buggy skinning

### ISSUE THREAD

**Issue by cmourglia** [STORM-IRIT/Radium-Engine#130]
The screenshot talks by itself. It's using only animation and skinning components.
The file : [Astroboy.zip](https://github.com/AGGA-IRIT/Radium-Engine/files/553280/Astroboy.zip)

![screen shot 10-26-16 at 02 39 pm](https://cloud.githubusercontent.com/assets/1152671/19726836/30e3bc50-9b8d-11e6-97b3-13dff71d1da1.PNG)

**Comment by mauriziokovacic** [comment]
Could you tell me more about this mesh?
It is coming from Maya? Blender?

I can see the initial skeleton is already in a different position in respect to the mesh. As soon as you start the animation, everything is getting huge, in comparison to the smallness of Astroboy.
That could be because of exporting with Blender without applying the scale factor to the bone transforms.

Anyway, there is without doubts a bug in the way we load models. Sometimes it is called Assimp, sometimes it is called "Maya and Blender are not compatible so don't expect you models to work". Sometimes could be my fault. 

I'll investigate on the problem

**Comment by louen** [comment]
So what about this issue ?

**Comment by hoshiryu** [comment]
Ping: Can't open any of the collada files because of unknown light type.
