### ISSUE TITLE
A general discussion on coding conventions

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#178]
This is to start the ~troll~ debate on coding conventions in Radium.

I encourage you to read the current convention (https://github.com/AGGA-IRIT/Radium-Engine/blob/master/conventions.md), and to discuss and argument if anything should be added, deleted or changed.

Here are the main rationales behind the decisions we had earlier in the project.

### Angle brackets in includes
First, I think include paths should never be defined relatively. This is obviously wrong:
```c++
#include "../../foo.hpp"
```

I argue that even this example is bad
```c++
#include "foo.hpp"
```
There is a semantic value in the full path of an include from the project's root (this supposes that the directory hierarchy makes sense, of course). There is more info in such a declaration than in the previous one :
```c++
#include "Core/Math/Foomatic/foo.hpp"
```
With files having dozens of includes this helps ordering them and identifying which ones might be useless.

So, now that I established that, from my point of view it is preferable to use the full paths, why force `<>` ? 
* Because it enforces the rule of no local paths (```#include <foo.hpp>``` will not work)
* Because it makes a simple and easy to remember rule.

### Brace style 

Why the Allman style you say ? 
* We now have big screens so we can spare a line or two
* In my experiences it allows easier modification of code e.g. when commenting you control structures
```c++
// if ( what() )
{
    doIt();
    doItNow();
}
```
Is still syntaxtically correct.

This also makes sense in the context of enforcing **braces everywhere**. The one-line `if` has been the source of many bugs. The canonical example is when you have
```c++
/// this is bad.
if (blah)
   doX();
```
and you add  another function
```c++
if (blah)
   doX();
   doY(); // oh, no !
```
Of course ```doY()``` is always executed regardless of the `if`. This is why I wish to enforce braces 
even for one-line `if`.
```c++
/// this is better
if (blah) {
   doX();
}
```

I argue that it's easier to visually scan for such constructs if you forces matching braces below every `if` statement.
```c++
/// this is even better
if (blah) 
{
   doX();
}
```

### Tabs vs spaces

Endless years of religious wars have not settled this debate. 
In an ideal world we would use tabs for indentations and space for alignments. The world is not ideal. Thus, it's just simpler to just use spaces everywhere.

### No exceptions, RTTI

Writing exception-safe code requires effort and is still awkward to use with low-level codes (which uses return code based errors), and we don't need no fancy error handling. 

RTTI is a bit more controversial. I argue that RTTI (especially dynamic cast) encourages bad design  and it adds a small penalty (more memory for each class) so it's not worth using in general.

**Comment by MathiasPaulin** [comment]
My name is Hebus .. Troll Hebus ... So, yep, I'll troll.

I agree that 
`#include "../../foo.hpp"`
is a nightmare and must be prevented.
but I think that 
`#include "foo.hpp"`
is very clear and indicates, "include the header foo from the current package"
while
`#include "Core/Math/Foomatic/foo.hpp"` 
might be interpreted as "include the header foo from the package Core/Math/Foomatic/ one may found in the implementation dependant location of search.

In the C standard, section 6.10.2, paragraphs 2 to 4 state:

2. A preprocessing directive of the form
`#include <h-char-sequence> new-line`
searches a sequence of implementation-defined places for a header identified uniquely by the specified sequence between the < and > delimiters, and causes the replacement of that directive by the entire contents of the header. How the places are specified or the header identified is implementation-defined.

3. A preprocessing directive of the form
`#include "q-char-sequence" new-line`
causes the replacement of that directive by the entire contents of the source file identified by the specified sequence between the " delimiters. The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read
`#include <h-char-sequence> new-line`
with the identical contained sequence (including > characters, if any) from the original directive.

4. A preprocessing directive of the form
`#include pp-tokens new-line`
(that does not match one of the two previous forms) is permitted. The preprocessing tokens after include in the directive are processed just as in normal text. (Each identifier currently defined as a macro name is replaced by its replacement list of preprocessing tokens.) The directive resulting after all replacements shall match one of the two previous forms. The method by which a sequence of preprocessing tokens between a < and a > preprocessing token pair or a pair of " characters is combined into a single header name preprocessing token is implementation-defined.

Definitions:
h-char: any member of the source character set except the new-line character and >
q-char: any member of the source character set except the new-line character and "

So, one can choose `<>` or `""` to include files.
I found a quick advantage of using "" rather than <> for including files related to the current project.
This allow to have a quick identification of standard dependance (included with <>) and intern dependance (included by `""`).
Note that `""` does not prevent to use a clean identification by Module/Submodule/CaptainIgloo/...

As we are on the header topic and inclusion, I agree with dots 1 and 2 (even if the name .hpp seems ugly) but I'm dubious about the 3rd. Why not use #pragma once instead of a guard that assume one know all the guards defined in a project ? #pragma once is supported by a lot of compilers (see [https://en.wikipedia.org/wiki/Pragma_once](https://en.wikipedia.org/wiki/Pragma_once) ) and much less error prone.

I agree with the point 4, but mention that it is not so well respected in the current code - this cause problems for me while integrating glbinding.

For point 5 refer to the discussion above.

For Point 6, I strongly disagree as soon as point 7 is not mandatory as well as the missing point 8 saying "Only include what is needed and not the whole universe" I reach a ton of problems simplifying the include graphs wile integrating glbinding to separate Qt and its somewhat crappy OpenGL management from core OpenGL. Integrating glew with Qt, for those who experienced this, is wayyyyyy more easy than glbinding. But glbinding is wayyyyyy more efficient and usefull than glew. 

Keep listening on this channel, soon the Troll Akläss will discuss about Functions, Scope, names, variable, code style and code design.

Cheers (or Roaaaaaarrrrrrrhhhhhh depending of your Troll Itude)

**Comment by nmellado** [comment]
:trollface:

**Comment by louen** [comment]
> `#include "foo.hpp"`
> is very clear and indicates, "include the header foo from the current package"
> while
> `#include "Core/Math/Foomatic/foo.hpp"`
> might be interpreted as "include the header foo from the package Core/Math/Foomatic/ one may found in the implementation dependant location of search.

I agree that the policy to use quotes for local code makes sense given the language definition,
however, this raises the question of what exactly is a "current package". Is it the whole project ? The library ? (Core / Engine / Guibase / etc) ? The module inside the library ? (e.g. Engine/Renderer) ? The current folder ? 

Let's say we are in the implementation of class `Toto` in library C.
Currently this looks like this: 
```c++
#include <C/Toto/Toto.hpp>

#include <cstring>
#include <A/Foo/Foomatic.hpp>
#include <A/Bar/Bar.hpp>
#include <B/Twiddling/Twiddler.hpp>
#include <C/Frob/Frob.hpp>
```
If I assume "current package" means the current library, here's what it  will look like :
```c++
#include "Toto.hpp"

#include <cstring>
#include <A/Foo/Foomatic.hpp>
#include <A/Bar/Bar.hpp>
#include <B/Twiddling/Twiddler.hpp>
#include "Frob/Frob.hpp"
```
Is that what you have in mind ?
I could agree to this (but the inconsistency between the last line and the other is kind of annoying).

> As we are on the header topic and inclusion, I agree with dots 1 and 2 (even if the name .hpp seems ugly)

* C files : `.c`, C header files `.h`
* C++ files `.cpp`, C++ header files `.hpp` 
what's not to like ? 

>  but I'm dubious about the 3rd. Why not use #pragma once instead of a guard that assume one know all the guards defined in a project ? #pragma once is supported by a lot of compilers (see https://en.wikipedia.org/wiki/Pragma_once ) and much less error prone.

I agree, we could use `#pragma once`. It seems the benefits outweights the potential risks.
Further discussion on the topic can be found on the interwebs :
* http://wiki.c2.com/?RedundantIncludeGuards
* https://www.reddit.com/r/cpp/comments/4cjjwe/come_on_guys_put_pragma_once_in_the_standard/d1j04te/

> For Point 6, I strongly disagree as soon as point 7 is not mandatory as well as the missing point 8 saying "Only include what is needed and not the whole universe" I reach a ton of problems simplifying the include graphs wile integrating glbinding to separate Qt and its somewhat crappy OpenGL management from core OpenGL. Integrating glew with Qt, for those who experienced this, is wayyyyyy more easy than glbinding. But glbinding is wayyyyyy more efficient and usefull than glew

I wholeheartedly agree. We need to enforce forward declaration as much as possible.

On the other hand, let's say your `class Toto` need a instance of `class Foo` and `class Bar`.
It just so happens that currently, `Bar` also needs a `Foo` instance, so `bar.hpp` includes `foo.hpp`. Does it make sense to include just `bar.hpp` or to include both ?
The argument for including both is that it is only incidental that `Bar` depends of `Foo` and in the future, a revision of `Bar` could remove this dependency. Having one include would make us modify the header of `Toto` which shouldn't be related.

**Comment by louen** [comment]
So, is there a proposition to change the coding convention or should I just close this issue for now ?

**Comment by dlyr** [comment]
BTW, we should define a common coding style, and I propose to use an automatic code formater (to have the same indentation, tab, openbrace style).
Either clang-format or astyle is fine, and with a predefined style is simplest
My opinion is to have a compact style mode ;) but I don't really care 
Check 
http://astyle.sourceforge.net/astyle.html#_Brace_Style_Options
for instance Google style.

**Comment by nmellado** [comment]
Independently of the style we use, I suggest we call the code formatter automatically as commit pre-hook (https://gist.github.com/wangkuiyi/7379a242f0d4089eaa75).
Of course, any developer should also configure properly is IDE to use the style definition.

**Comment by louen** [comment]
There is a `astylerc`file in the root of the Radium folder hierarchy (although I doubt it has ever been used). 
I would be all in favor of a pre-commit formatting (but we have to make sure that it works on Windows too !)

**Comment by nmellado** [comment]
Cording guidelines need to be clearly explained (and the process to use it with hooks and IDE) as suggested here: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by nmellado** [comment]
FYI: astyle can be used with Visual Studio, but not directly using the file today provided.

**Comment by MathiasPaulin** [comment]
I'm using Clion as IDE. Clion proposes strong formating facilities (pre-commit, on the fly), using various predefined style. I've not found, yet, how to integrate astyle definiton but I can quite easily parameterize the IDE to follow what I understand in the astylerc. I've just one question : why CRLF at line end ? ...

**Comment by dlyr** [comment]
I propose to use clang-format with standard style (say llvm), it will ease a lot settings of each ide, and do not change our habits ;)
I could commit a set of script one can add as pre-commit hook to format their files (at least for linux/macos)

**Comment by nmellado** [comment]
+1 for llvm style.
+1 for your hooks ;)

**Comment by MathiasPaulin** [comment]
+1 LLVM.
The style is clearly explained and justified at this [URL](http://llvm.org/docs/CodingStandards.html).
```http://llvm.org/docs/CodingStandards.html```
