### ISSUE TITLE
ShaderProgramManager instanciation (was Singleton design)

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#208]
Hi, 
I would like to discuss the singleton macro.
Why do we need a `createInstance` and `replaceInstance`.
I would find it simpler to have only `getInstance()`, and if no instance already created, the singleton has to create one. see https://github.com/AGGA-IRIT/Radium-Engine/blob/master/src/Core/Utils/Singleton.hpp#L26
++

**Comment by dlyr** [comment]
Maybe the question is also, why do we need singleton with constructor with parameters. Maybe a init method could do the work.

**Comment by louen** [comment]
Ok, so there are two questions and I'll try to answer them.

Why do we need `createInstance()` ? It all boils down to *"why do we need singletons ?"* actually.
 
To be honest, singletons are just glorified global variables (which as every programmer knows, are evil). In theory we could do without them. We could encapsulate them in a "Context" structure and pass this structure around everywhere in the code, but that would be inconvenient or ugly. 

But in essence, in Radium there are only few instances of a singleton. In principle there should only be the engine instance, and the other "unique" components (e.g. the various managers etc) are defined as members of the Engine. Thus if you want to grab the RO manager, you ask for the engine and you get the RO manager from it.

Now the difference between and singleton and a global variable is that singletons allow some control the moment where the instance is created. In C++ global variables are initialized before `main()` in an *undefined order*. So if you want to control in which order your global's instances are created, you're out of luck.  Hence the singleton.

Now the strategy often seen in the singleton pattern is to tie the instantiation to the first access. This is a kind of  *lazy instantiation* which is a very valid strategy. But here, we chose to have more control as to who initializes the singleton instance and when, so the . Indeed, you could subclass `Singleton` with a `LazySingleton` for which `createInstance()`  is private and `getInstance()` calls it on the first time. Here we chose to keep the basic singleton adaptable because we want precise control over when our major singleton instance (`RadiumEngine`) is created.

The same rationale goes for the constructor arguments and the `init()` method.  Why request singleton classes to have an empty constructor *by default* ? There may be cases where it does not makes sense.

**Comment by dlyr** [comment]
Fine for me, the question arise from the fact that a Renderer create a singleton (which is very bad if you have multiple renderer). I have corrected this, in a forthcoming PR ;)

**Comment by hoshiryu** [comment]
> But in essence, in Radium there are only few instances of a singleton. In principle there should only be the engine instance, and the other "unique" components (e.g. the various managers etc) are defined as members of the Engine. Thus if you want to grab the RO manager, you ask for the engine and you get the RO manager from it.

Then we could get rid of all the singletons but the one on the Engine, but I think that would put a too high restriction. For example, when dealing with high frequency devices (such as haptics), one might want to use one engine to deal with those, while having another (or more) engine dealing with low frequency tasks (such as animation, physics...). Having a Singleton on the Engine prevents such a case.

On the other hand, possibly having multiple engines means that we need a way to access the current one to get access to the resources through the managers (may be either singletons -- which seams fine -- or engine attributes) when performing tasks.

**Comment by dlyr** [comment]
I have tested to initialize the `ShaderProgramManager` in the engine initialization, but glo`b`jects is not init a this point. The question is : "is it a good idea to have GL in Engine or does GL stay in viewer ?"
If GL stay in the viewer only, then the viewer ctr the `ShaderProgramManager` and initalize it.

**Comment by louen** [comment]
Well the Engine relies on OpenGL for now. I don't think we want to go away from that model for now, I guess.

**Comment by louen** [comment]
To reply to @hoshiryu's post. No, there must be only one engine. 
The high vs low frequency thing can be handled at the task level (by spawning low frequency tasks once every *n* frames)

**Comment by MathiasPaulin** [comment]
C++ Core Guidelines by Bjarne Stroustrup and Herb Sutter
**Avoid singletons**
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i3-avoid-singletons
