### ISSUE TITLE
Merge Hugo branch to have editable pipeline

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#230]
Because we should always merge before the end of the work ...
so branch hugo is totally out of date and need to be merge in master.
++

**Comment by Zarzwick** [comment]
Hugo here! It is indeed totally out of date. Since there is some cleanup these days within the Radium code, I deleted the `hugo` branch from the upstream repository so that it now lives only on my fork.

This is very low priority, but still, in the future days/weeks what I'm going to do is to try to make it work again. However, even in a working state the current architecture isn't great, for some reasons (the dependence to imgui, the plugin-but-not-that-much organisation which is ad-hoc to the forward renderer of 2016...). I have some ideas but we may discuss of it before any refactoring, and anyway it must be compiling again first.

**Comment by louen** [comment]
I close this issue as a won't fix, and maybe somebody opens a feature issue for editable pipeline
