### ISSUE TITLE
Can't maximize/resize main-app window

### ISSUE THREAD

**Issue by Nalonoid** [STORM-IRIT/Radium-Engine#288]
Hello,

I can't maximize nor resize the main-app while the left tree/menu is attached inside the window. It prevents me from seeing the whole window, cutting the bottom part.

![image](https://user-images.githubusercontent.com/17992775/36126209-cd4a3e9e-1057-11e8-9586-f40c1f9e8a43.png)

If I right click on the menu and detach the left part, then I can resize the main window correctly.

May it help, here is my configuration :
Display 1920*1080
Linux - Ubuntu 17.10 MATE
compiz
Qt 5.9.1
OpenGL 4.5
g++ 7.2.0

**Comment by dlyr** [comment]
Seems like the menu is bigger than your screen

**Comment by Nalonoid** [comment]
After further testing, it works well with another computer using a 1920*1080 display too, so I'm not sure it is really screen related. (And I don't think most users use screens with a resolution higher than 1920*1080) Same desktop environment, different hardware though. (Both are using NVIDIA 384.111 driver)

**Comment by dlyr** [comment]
Could you post two screenshots (fullscreen) to see the differences ?
I suspect the first computer to have larger GUI.
One solution is to compact GUI, another is to encapsulate GUI into a QScrollArea

**Comment by nmellado** [comment]
I see two other solutions (my favorite is 1):
 1. Move the Plugins interface to another QDockWidget, that can be moved independently from the other parts of the interface.
 2. Change the setting of the QTabWidget containing the Plugins interface, like this:
![untitled](https://user-images.githubusercontent.com/6310221/36199020-986030a4-1178-11e8-8a2a-313231d76791.png)

**Comment by ThibaultLejemble** [comment]
I have the same issue with my _1920x1080_ display, while it's working correctly on my _1920x1200_ secondary display. I can't maximize the main window because it's too high, so the main window is slightly too big for the screen.

I didn't test solution 1 (extra _QDockWidget_ for plugins) but I have tested solution 2 (set _tabPosition_ to _North_) and it doesn't resolve the problem since the issue is precisely the height.

The problem comes from the _QTabWidget_ which takes as minimum height the maximal one of its own tabs. Currently, it's the _MeshFeatureTracking_ tab (which is quite high) that commands the size of the _QTabWidget_ and thus the final size of the whole _QDockWidget_.

I quickly fix the problem by changing the minimum height of the _QTreeView_ (entity tree at the top) from 150 to 100 (in case the tree contains too many items, a scroll bar appears so it's not problematic).

Another solution is to, as dlyr said, encapsulate tabs in a _QScrollArea_. I do this for my plugin and it works find, although having scroll bars inside tabs can make the UI heavy to use.

**Comment by nmellado** [comment]
Thanks @ThibaultLejemble for your feedback.
I'm not fan of _QScrollArea_, as it hides some part of the UI.
I would push for a dedicated _QDockWidget_

**Comment by MathiasPaulin** [comment]
I have the same issue on my retina display on MacOs. OK for a dedicated QDockWidget but we also must encapsulate tabs in scrollArea so that the dock might be mouse-manipulate on whatever the display we have.
