### ISSUE TITLE
Crash on reset scene

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#314]
When resetting the scene, even if empty (just the frame and grid), the main app crashes.
Unfortunately, I couldn't figure out what is happening: the app segfaults when resetting the camera. More precisely, when re-attaching the light to the reset camera, right when setting the light's direction.
Since all pointers are ok there, I guess the segfault comes from somewhere else.
By the way, lights doesn't seem to be destroyed by the LightManager nor the Renderer, but maybe I missed something.

**Comment by MathiasPaulin** [comment]
Well, this is due to the interaction of several bad designs : one concerning the Viewer/Camera association, the other concerning Renderer/Light manager.
For now, I'll be able to patch the master-v1 so that this will not occur but this patch will not be fair.
Instead of applying patches that depends on the way one use the Engine, we must identify all these problem and make the correct implementation.

So for this crash, some explanations.
In order to unify the light management between renderers and to simplify the file loading system, Lights are now components attached to entities. The headlight (the light attached to the camera is then a component attached to an engine global entity).
At rendering, the headlight is added to the renderer's light manager and used at each rendering pass.
When clearing a scene, all entities are deleted. So is the headlight. But there is no way to remove the headlight from the current renderer light manager. More, several pointer that reference the light could not be reseted (no shared pointer nor unique pointer ...). So when using a deleted pointer, the renderer crashes.
This was for the problem due to light manager that result from the reset camera mechanism in the renderer ... and then to the second design problem concerning the Viewer/Camera association. We can rewrite the reset camera method so that the headlight is still alive after that but will have a problem after that on the Viewer::startrendering method.

The better way to solve this problem is to make the camera an entity of the system and attach the headlight component to this entity. This will have several impacts on the whole Engine/Application ecosystem but will be more general and robust for future development.

More to come with code snippets and local fixes ...
