### ISSUE TITLE
Creating textures

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#316]
When creating a new texture with the current implementation, the only ways are to:
 - manually create the Texture, which means skipping the TextureManager
 - call `TextureManager::addTexture(name)`, which means the texture parameters (filters, wrap, ... ) cannot be changed from the default ones
 - call `TextureManager::getOrLoadTexture(name)`, idem
 - call `TextureManager::getOrLoadTexture(TextureData)`, which is slightly better but enforce manually loading the texture image beforehand, otherwise the texture parameters will be ignored.

In all cases, the texture parameters cannot be changed afterwards.

Moreover, when trying to create a new texture, the app crashes on `globjects::Texture::create( GL_TEXTURE_2D );`

The proposed solution (from @MathiasPaulin) is to rename `TextureManager::addTexture(name)` into `TextureManager::loadTexture(name)` and make it only load the texture image, leaving the Texture creation / generation / insertion to `TextureManager::getOrLoadTexture(name)`.
Also, should it be private?
Regarding the parameters modification, the corresponding methods will be added.

**Comment by hoshiryu** [comment]
I still have issues creating a texture within my plugins, the app still crashes on `globjects::Texture::create( GL_TEXTURE_2D );`
Here is my code:
``` c++
auto tex = Ra::Engine::TextureManager::getInstance()->getOrLoadTexture( name );
mat->addTexture( Ra::Engine::BlinnPhongMaterial::TextureSemantic::TEX_DIFFUSE, tex );
```
What is wrong with that?

**Comment by nmellado** [comment]
@MathiasPaulin @hoshiryu , can you try to fix this in PR #319 ?

**Comment by MathiasPaulin** [comment]
RTFM ... wel, the manual is not so explicit : all OpenGL dependent structures must be acquired and initialized only when the OpenGL context is available. Ther is a mthod, in ``RadiumPluginInterface``to do that : 
```
virtual void openGlInitialize( const PluginContext& context, const QOpenGLContext* openGLContext );
```
Do you create openGL stuff in your plugin before OpenGL was initialized ? It seems it is the case. I do that on my plugins, in the method ``void PbrPlugin::openGlInitialize( const Ra::PluginContext &context, const QOpenGLContext *openGLContext )`` and all is fine. 
Do you really need to initialize OpenGL stuff (even partly) before openGL context was initialized ?
Why do you not put this code in the appropriate Plugin init method (``openGlInitialize``)

I'll be thinking on a Texture ecosystem rewriting (because I need several concepts not available in the current engine, and eve more, not doable) that will simplify texture management. 

But, if you give me a good justification of having automatic deferred initalization of Material openGL state, I can make, for the moment, the method ``TextureData& BlinnPhongMaterial::addTexture( const BlinnPhongMaterial::TextureSemantic& semantic, const TextureData& texture );`` public in the PR #319. But this method is specific to ``BlinnPhongMaterial`` and is not on the Material interface. Must be used with care and OpenGL initialization must be postpone in the plugin.

**Comment by hoshiryu** [comment]
Yes, OpenGL is initialized when I try to create the texture... I'll try creating all the textures in the mentioned method.

**Comment by hoshiryu** [comment]
Ok, now it runs but the textures are all black...

**Comment by hoshiryu** [comment]
Ok, closing this one and opening a new one
