### ISSUE TITLE
Distributing Radium-based apps

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#331]
The app I'm working on is ready for distribution.
What I would like to do is just to zip it so that people can download/unzip/launch the app.
For windows, since all dlls have to be in the binary directory, there is no problem.
But for Linux (and I guess it's the same for Mac) I had issues with the rpath used for the app and the libraries.
The solution I came up with is to:
- add the relative path "." to the rpath used by the radium libraries:
`set_target_properties(<target> PROPERTIES LINK_FLAGS "-Wl,-rpath,./")`
- copy all the libraries (radium's and 3rdParty's) into the bin directory

thus mimicking windows' way.

I hope this may help others with preparing their app's distribution.
I'm also looking forward for the under-investigation Radium install procedure and how it will affect app distribution / packaging.

**Comment by nmellado** [comment]
As discussed, the proper way to do that would be to upgrade the cmake configuration to add install target.
This would however affect the workflow of several users in the team, so we decided to not fix it for now.
So your trick is all right, and can be used sometime, but must be considered as a patch.

Note: this issue is related to one of the milestone for Radium Stable Release https://github.com/STORM-IRIT/Radium-Engine/projects/2#card-7560506, and is expected to be solved by this time.
Contributions are welcome ;)

**Comment by hoshiryu** [comment]
closing this one, updated version at #344
