### ISSUE TITLE
Grid, Tex, std::vector and Eigen

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#412]
I just notice that `Ra::Core:::Grid` use plain std::vector, which is fine in general, but not for Eigen types
[as stated here](https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html).

https://github.com/STORM-IRIT/Radium-Engine/blob/73737a822d3b1a1bc9b80d52d303c6107659c57d/src/Core/Containers/Grid.hpp#L234

Do not know how to fixit, maybe a partial template specialization or add `EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION` in RaCore.hpp ?

**Comment by nmellado** [comment]
There is a functionality clash between `Grid` and a new structure called `Volume` which generalize the concept to functional representations, sparse and dense grid storage. Volume are currently tested in another branch, but hopefully I should be able to submit it soon. 

So, just to say: we could try to solve this problem with the Volume implementation, and replace Grid by this one. Instead of doing this twice.

Another remark, the concepts implemented for Volume also stand for 2D textures. So we could have a n-dimensional abstraction, explicitely specialized for the 2D and 3D case.

**Comment by dlyr** [comment]
Some sort of duplicate of #797, so I close this one.
