### ISSUE TITLE
Handle loading of skeleton-only scenes

### ISSUE THREAD

**Issue by louen** [STORM-IRIT/Radium-Engine#464]
**Current behaviour** :  loading a FBX file containing only an animation skeleton doesn't add anything to the current scene in Radium.

**Expected behaviour** : the Animation Plugin should create a skeleton, display the bones and play animations (if any) even if there is no mesh associated with it.

**Platform details** : current master on Windows / VS2017 x64

**How to reproduce** :  load attached FBX file [01_02.zip](https://github.com/STORM-IRIT/Radium-Engine/files/3488238/01_02.zip) from CMU's motion capture database.
Loading fails with `- 15:53:52 WARNING: File "01_02.fbx" has no usable data. Deleting entity...`

The main culprits seem to be
* in  `AssimpFileLoader.cpp` (around line 90), which aborts mid-load if there is no geometry data
```c++
bool ok = std::any_of( fileData->m_geometryData.begin(),
                               fileData->m_geometryData.end(),
                               []( const auto& geom ) -> bool { return geom->hasFaces(); } );
```

* in `AssimpHandleDataLoader.cpp` , the function `AssimpHandleDataLoader::sceneHandleSize()` counts only bones associated with meshes.

**Comment by nmellado** [comment]
Thanks for the detailed report @louen.

**Comment by hoshiryu** [comment]
Well, the issue is more complex.
For sure we should test point clouds with

**Comment by hoshiryu** [comment]
The problem is a bit more complex.
- first, we should test point clouds with `fileData->hasGeometry() && !ok`
- second, we have to check the Assimp structure for bones not bound to a mesh, which is a bit cumbersome since such Assimp Nodes would just store a transformation and its children, just as any other node (mesh, transform)
Nevertheless, I will take a look at this ;)
