### ISSUE TITLE
Resources path issue

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#513]
Hmm, I still have the issue on resources location:
 - in Release (wrong folder name due to missing `/`):
```
- 10:41:11 INFO:  *** Loading Plugins ***
- 10:41:11 ERROR: Cannot open specified plugins directory /home/hoshiryu/dev/Radium/Radium-Engine/Bundle-GNU/binPlugins/lib/
- 10:41:11 ERROR: An error occurred while trying to load plugins.
```
- in Debug:
```
- 10:41:47 INFO:  *** Loading Plugins ***
- 10:41:47 ERROR: Cannot open specified plugins directory Plugins/lib/
- 10:41:47 ERROR: An error occurred while trying to load plugins.
```
I fixed it by changing line 19 of file `src/Core/Resources/Resources.cpp` but this might not be the ideal solution.

**Comment by MathiasPaulin** [comment]
In the application, if you go to the menu File-->Plugin-->Add plugin path <Ctrl-P> and you browse until your plugin directory. Is it OK ?
Beware that you can't load plugins compiled in debug mode while the app is in release mode (and vice-versa)

**Comment by nmellado** [comment]
Regarding the debug/release thing, Radium should disambiguate this case by itself: plugins with the wrong build type will be ignored (a message should be printed in `stdout`).

**Comment by MathiasPaulin** [comment]
Well, There is no problem with resource locator. 
If the plugins are configured and installed the right way (see below), all is OK. If they are installed in the correct expected directory for the Radium Bundle, (see below), all is OK also.

**Comment by MathiasPaulin** [comment]
This issue is the result of a specific (and erroneous) installation of Plugins in the Radium Bundle.
Even if this is allowed (and the cmake radium configuration , as written below, gives the correct configuration option), it is not encouraged. You can load plugins from anywhere at application startup (and plugins are not restricted to main-app). The first time you want to use a Plugin, go through the File/Plugin menu of the main-app and select the directory where the plugin is located.
If you want to install plugins in the Bundle, that is not recommended, you must conform to the required directory structure or use automatic configuration in your plugin cmake.
The simpler way of installing plugins in the Bundle (that is not recommended) is to configure plugin install in the plugin cmake using : 
```
configure_radium_plugin_install(
        NAME ${PLUGIN_NAME}
        INSTALL_IN_RADIUM_BUNDLE
        RESOURCES ${CMAKE_CURRENT_SOURCE_DIR}/Resources/Shaders
)
```
If you want to install the Plugins using another method (such as doing a
`-DCMAKE_INSTALL_PREFIX=the/location/in/the/bundle` at cmake configuration), respect the following structure : 
- Root of the Bundle
    - lib (the directory with the BUNDLE libs)
   - include (the directory with the BUNDLE include)
   - bin (the directory with the BUNDLE binaries)
   - Resources (the directory with the BUNDLE resources)
   - Plugins  (the directory with the BUNDLE plugins)
      - lib (the directory with the .so, .dylib or .dll of the plugins)
      - Resources (the directory with the internal resources of plugins
   - ... others BUNDLED files and directory

Recall that the BUNDLE must be relocatable and that if you dont install plugins using the cmake configuration, there will not be relocatable.
If you don't care about relocatability, you can install plugins manually (using `-DCMAKE_INSTALL_PREFIX`. But, if you do not install plugins in the right directory, the Resource locator will not find them as it has no idea of where to search for. 

This issue will be closed in the next days as there is no fix other than a correct usage of the installation procedure.
