### ISSUE TITLE
system wide lib interfere with radium external

### ISSUE THREAD

**Issue by dlyr** [STORM-IRIT/Radium-Engine#584]
On debian bullseye, when `libglm-dev` is installed, then link fail for globjects.
```
[ 84%] Performing build step for 'globjects'
[  1%] Linking CXX shared library ../../libglobjects.so
/usr/bin/ld: cannot find -lglm
```

to reproduce:
```
sudo apt install libglm-dev
```
cmake configuration fail
```
sudo apt remove --purge libglm-dev
```
cmake configuration pass

So it seems that the library search pass is not set correctly during configuration of globjects regarding glm

**Comment by MathiasPaulin** [comment]
@dlyr Is this issue still alive ?

**Comment by dlyr** [comment]
yes

**Comment by dlyr** [comment]
```bash
[100%] Linking CXX shared library ../../libglobjects.so
/usr/bin/ld: cannot find -lglm
collect2: error: ld returned 1 exit status
```

**Comment by MathiasPaulin** [comment]
I think I found the problem : find_package is in module mode and we prefer first config mode. 
https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html#variable:CMAKE_FIND_PACKAGE_PREFER_CONFIG
Can you test what happens when adding `    -DRADIUM_EXTERNAL_CMAKE_OPTIONS=TRUE` at line 32 of the file `cmake/ExternalInclude.cmake` (definition of RADIUM_EXTERNAL_CMAKE_OPTIONS)?
Adding this to the cmake options passed to the configuration of externals will ask to search first for the compiled external instead of the system wide library (see the above doc link).

**Comment by dlyr** [comment]
Still present, the find_package(glm REQUIRED) of the globjects config still ignore theses options
I have tested 
```
message(STATUS "XXXXXXXXXX---------XXXXXXXXXXXXXXXXXXXXXXXXXx ${glm_DIR} AAAAAAA")
find_package(glm REQUIRED)
message(STATUS "${CMAKE_FIND_PACKAGE_PREFER_CONFIG}XXXXXXXXXX---------XXXXXXXXXXXXXXXXXXXXXXXXXx ${glm_DIR} AAAAAAA")
```
outputs 
```
-- XXXXXXXXXX---------XXXXXXXXXXXXXXXXXXXXXXXXXx /export/home/caravage/vanderha-local/Repositories/Radium-Engine/Bundle-GNU/lib/cmake/glm AAAAAAA
-- TRUEXXXXXXXXXX---------XXXXXXXXXXXXXXXXXXXXXXXXXx /usr/lib/cmake/glm AAAAAAA
```
(you have to remove the reset hard in external/Engine CMakeLists.txt to test this)

**Comment by MathiasPaulin** [comment]
Got it (but without fix for now)
the error comes from a wrong value of the `${glm_DIR}` variable (set in `external/Engine/CMakeLists.txt`) when configuring globjects.
By looking into the bundle, glm package config file is installed into `Bundle-GNU/lib/x86_64-linux-gnu/cmake/glm` but the `glm_DIR` variable is set to `Bundle-GNU/lib/cmake/glm`
by setting the `glm_DIR` variable to the good directory, the glm package found is the good one, and there is no need of `CMAKE_FIND_PACKAGE_PREFER_CONFIG`.

I try to fix the instqllqtion of glm so thqt we can set `glm_DIR` in a compiler independant way.
