### ISSUE TITLE
Topological Mesh requires normal vectors, but they are optional

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#688]
A mesh can exists even if the normal vectors are not set.
However, the constructor of `TopologicalMesh` expect (without tasking or requiring it) and read this attribute:
https://github.com/STORM-IRIT/Radium-Engine/blob/a50a3b45a694855e2fbf2a657656a5e98605af34/src/Core/Geometry/TopologicalMesh.inl#L119
This cause a segfault at runtime.

A way to fix this would be to test if the normal buffer is empty, and skip the normal attribute setting in that case.

**Comment by dlyr** [comment]
Right, for historical purpose we have mandatory normals attributes. 
But after a quick check it's not the case in Engine::Mesh anymore since everything is treated as attrib, even position.
A more generic way to do this is to only use Core::TriangleMesh attribs, and potentially have an alias for normals() in TopologicalMesh.
As a side note this problem is remove when using wedges (currently normals are stored twice, one wedge and on halfedges, but only one is necessary)
