### ISSUE TITLE
Wedges on multiple attributes create artificial discontinuities

### ISSUE THREAD

**Issue by chemseddinehimeur** [STORM-IRIT/Radium-Engine#712]
After processing a couple of models on Blender, I noticed that the current wedge structure mixes normal discontinuities with other attributes. 
On Blender we have the concept of sharp edges (contains multiple normals) to mark geometry discontinuities on a given mesh, and soft edges were the normals are continuous. which are separate  from other attributes such as texture cut lines and such. 
On the current version of Radium the wedge structure mixes the two discontinuities so after any process on a mesh in Radium that involves wedges, we end up with an end result were we have sharp edges along texture lines and other discontinuities.

**Comment by dlyr** [comment]
Could you provide the client code and what is expected ?

**Comment by dlyr** [comment]
I have face something similar as a starting point you can see 

https://github.com/dlyr/Radium-Engine/blob/64fd58dc35d963918aae26f0ba265f949f9fe60e/src/Core/Geometry/TopologicalMesh.hpp#L735
https://github.com/dlyr/Radium-Engine/blob/64fd58dc35d963918aae26f0ba265f949f9fe60e/src/Core/Geometry/TopologicalMesh.hpp#L184

We will discuss more indeep afk.

**Comment by nmellado** [comment]
What is the status of this issue ?

**Comment by dlyr** [comment]
Well the problem was mostly due to bad wedge management. 
Now wedge is solved (well will be in #719) most of the problems are sovled.
Nevertheless, the issue of attribute interpolation on their own is not sovled.

So the roadmap is to:
- manage wedge attribute interpolation
- create some kind of wedge merging by attribute so that wedges with equal values for one attributes are processed as one wedge
- add tests ;)
I think wedge need to be a mapping to "core or engine vertices" but we can provide helpers to ease user interaction with topology and attirbutes

**Comment by dlyr** [comment]
Fixed by #719 
I open a new issue concerning the removal of deprecated topological mesh and subdividers
