### ISSUE TITLE
Doc: difficult to find doc to cmake config

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#888]
In these pages:
- https://storm-irit.github.io/Radium-Engine/release-candidate/apps.html
- https://storm-irit.github.io/Radium-Engine/release-candidate/develplugin.html (this one is a bit better)

It is not clear that Radium provides some `cmake` utilities (e.g., the installation functions) that need to be considered.

Theses pages need to be updated, so we add:
- a link to this page: [How to write your own application](https://storm-irit.github.io/Radium-Engine/release-candidate/apps.html)
- a more comprehensive introduction/overview on what is provided by radium, and what is not.

**Comment by MathiasPaulin** [comment]
From this page [Developer manual](https://storm-irit.github.io/Radium-Engine/release-candidate/develmanual.html), which can be accessed from the left menu entry `Developer manual` the [CMake setup](https://storm-irit.github.io/Radium-Engine/release-candidate/cmakeutilities.html) gives all the information about cmake utilies and how to configure an app/plugin/library. What do you need more ?

**Comment by dlyr** [comment]
At least : fix bad link https://github.com/STORM-IRIT/Radium-AppExample
For plugin, maybe state clearly that `configure_radium_plugin` is provided from `find_package(Radium REQUIRED Core Engine PluginBase)` and link [CMake setup](https://storm-irit.github.io/Radium-Engine/release-candidate/cmakeutilities.html) on the plugin howto page.

**Comment by hiergaut** [comment]
I wanted to use radium as an external library to create an executable. I found this page in the Radium doc which seemed to do the job (https://storm-irit.github.io/Radium-Engine/release-candidate/basicsRadiumSubmodule.html).
So I created my own main.cpp and a CMake file following the instructions given in this page documentation.
After compilation it turns out that the dlls are not copied, I did not have in mind that there was a function in Radium proposing this because I thought that on this page there was all the necessary information to compile and execute a program using Radium as library.
So you have to add this informations :
#don't forget to add this line to copy dlls on win system
configure_radium_app(NAME ${PROJECT_NAME})
Indeed this information can be found in the CMake setup link at the bottom of this page, but I considered it was an additional information.

**Comment by hiergaut** [comment]
Thanks for the corrective.
